### ISSUE TITLE
delay function

### ISSUE THREAD

**Issue by krthr** [JuanDavidSolano/Cata#1]
Hey! Puppeteer provides a function called `wait`: https://pptr.dev/#?product=Puppeteer&version=v4.0.0&show=api-pagewaitforselectororfunctionortimeout-options-args

```js
// wait for 1 second
await page.waitFor(1000);
```

**Comment by JuanDavidSolano** [comment]
Thanks, I'm gonna change it to use the puppeteer function 😄
